### ISSUE TITLE
Error executing script

### ISSUE THREAD

**Issue by bassopt** [CitraIT/migrate_pfsense#1]
Hi.
Tried your script with a backup from pfsense+ 23.01.

CA OpenVPN importada com sucesso!
Traceback (most recent call last):
  File "/Users/xxxxxt/migrate_pfsense/src/migrate_pfsense.py", line 60, in <module>
    migrate_certificates(fw, "pfsense.xml")
  File "/Users/xxxxxx/migrate_pfsense/src/functions.py", line 398, in migrate_certificates
    firewall.import_ca(ca)
  File "/Users/xxxxx/migrate_pfsense/src/firewall.py", line 347, in import_ca
    'key': b64decode(ca["prv"]).decode(),
                     ~~^^^^^^^
KeyError: 'prv

I'm using OSX for this latest python 3 version.

**Comment by 2600box** [comment]
I am sure you moved on from this long ago, but I faced the same issue and so worked through errors I encountered to either work around or ignore errors. I mention this in case anyone else comes looking and wants to try with my patches: https://github.com/CitraIT/migrate_pfsense/pull/2
